# Included in https://github.com/stablecc/scclib under directory import/googletest/googletest

BASE = ../../..

NAME = gtest

CPPFLAGS += -isystem include -I .

SRCS = src/gtest-all.cc

include $(BASE)/make/sl.mk
